{{- with .Values }}
{{- if .create_externalSecret }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
{{- with .ex_secret }}  
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  refreshInterval: {{ .refresh | quote }}
  secretStoreRef:
    name: {{ $.Values.secret_store.name }}
    kind: {{ .store_kind }}
  target:
    name: {{ .target.name }}
    creationPolicy: {{ .target.cr_policy }}
  data:
  - secretKey: {{ .secret_key }}
    remoteRef:
      key: {{ .key_ref }}
{{- end }}        
{{- end }}
{{- end }}
