{{- if .Values.ingresses.create }}
{{- with .Values.ingresses.example }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  annotations:
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .class_name }}
  {{- range .rules }}  
  rules:
    - http:
        paths:
          {{- range .http.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | quote }}
            {{- with .backend.service }}  
            backend:
              service:
                name: {{ .name }}
                port:
                  number: {{ .port.number }}
            {{- end }}
          {{- end }}
  {{- end }}        
{{- end }}
{{- end }}
