{{- with .Values }}
{{- if .create_secretStore }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .secret_store.name }}
  namespace: {{ .namespace }}
spec:
  {{- with .secret_store }}
  provider:
  {{ .provider.name | indent 2 }}:
      service: {{ .provider.svc }}
      region: {{ .region }}
  {{- end }}    
      auth:
        jwt:
          serviceAccountRef:
            {{- include "sa-metadata" . | indent 12 }}
{{- end }}
{{- end }}
