deploy:
  name: fnt-deploy
  label:
    key: app
    value: fnt-deploy
  container:
    name: fnt-cnt
    cnt_port: 80
  image: 
    name: 637423489195.dkr.ecr.eu-north-1.amazonaws.com/client-repo
    tag: 3bb33d5710eb631fa8f6482160922c6dd6da5bfb
 

service:
  name: fnt-svc
  port: 8088
  targetPort: 80
