deploy:
  name: srv-deploy
  label:
    key: app
    value: srv-deploy
  container:
    name: srv-cnt
    cnt_port: 4000
  image: 
    name: 637423489195.dkr.ecr.eu-north-1.amazonaws.com/server-repo
    tag: ddd8d47b856c6b7cded9fdedf7e0869172a38876
 
service:
  name: srv-svc
  port: 8084
  targetPort: 4000
 

