deploy:
  name: srv-deploy
  label:
    key: app
    value: srv-deploy
  container:
    name: srv-cnt
    cnt_port: 4000
  image: 
    name: 637423489195.dkr.ecr.eu-north-1.amazonaws.com/server-repo
    tag: 2b906290c12e92df4026f4517f74352ee8d12b77
 
service:
  name: srv-svc
  port: 8084
  targetPort: 4000
 

