deploy:
  name: srv-deploy
  label:
    key: app
    value: srv-deploy
  container:
    name: srv-cnt
    cnt_port: 4000
  image: 
    name: 637423489195.dkr.ecr.eu-north-1.amazonaws.com/srv
    tag: 51cf4b6a

service:
  name: srv-svc
  port: 8084
  targetPort: 4000

    
