apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ex-secret-name
  namespace: somens
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: k8s-secret-store
    creationPolicy: Owner
  data:
  - secretKey: m-key
    remoteRef:
      key: m-eks-secret
