name: Apply terraform infrastructure

on:
  push:
    branches:
    - main
    paths:
    - 'some-terraform/**'
  workflow_dispatch:

jobs:
  Terraform-job:
    name: Tf-job-name
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::637423489195:role/${{ vars.OIDC_ROLE_NAME }}
          aws-region: eu-north-1

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.3.5"

      - name: Apply Terraform infrastructure
        working-directory: terraform
        run: |
          terraform init
          terraform plan
          terraform apply --auto-approve


